version: "3.8"

services:

    lichessbot:
        image: lichess-bot
        env_file: .env
        
    lilagif:
        image: benmitchell58/lila-gif:latest
        ports:
            - 6175:6175
        expose: 
            - "6175"